:_mod-docs-content-type: SNIPPET
.Example `ImageSetConfiguration` CR for {lvms}
[source,yaml,subs="attributes+"]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
storageConfig:
  registry:
    imageURL: example.com/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-{product-version}
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v{product-version}
    packages:
    - name: lvms-operator
      channels:
      - name: stable
  additionalImages:
  - name: registry.redhat.io/ubi9/ubi:latest
  helm: {}
----
+
--
`archiveSize: 4`:: Set the maximum size (in GiB) of each file within the image set.
`storageConfig:`:: Specify the location in which you want to save the image set. This location can be a registry or a local directory. You must configure the `storageConfig` field unless you are using the Technology Preview OCI feature.
`imageURL: example.com/mirror/oc-mirror-metadata`:: Specify the storage URL for the image stream when using a registry. For more information, see _Why use imagestreams_.
`- name: stable-{product-version}`:: Specify the channel from which you want to retrieve the {product-title} images.
`graph: true`:: Set this field to `true` to generate the OpenShift Update Service (OSUS) graph image. For more information, see _About the OpenShift Update Service_.
`- catalog: registry.redhat.io/redhat/redhat-operator-index:v{product-version}`:: Specify the Operator catalog from which you want to retrieve the {product-title} images.
`- name: lvms-operator`:: Specify the Operator packages to include in the image set. If this field is empty, all packages in the catalog are retrieved.
`- name: stable`:: Specify the channels of the Operator packages to include in the image set. You must include the default channel for the Operator package even if you do not use the bundles in that channel. You can find the default channel by running the following command: `$ oc mirror list operators --catalog=<catalog_name> --package=<package_name>`.
`- name: registry.redhat.io/ubi9/ubi:latest`:: Specify any additional images to include in the image set.
--
