// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-core-ref-components.adoc

:_content-type: REFERENCE
[id="telco-core-security_{context}"]
= Security

New in this release::

* [https://issues.redhat.com/browse/CNF-7349[CNF-7349]] Rootless DPDK pods create a tap device in a rootless pod that is used to inject traffic from a dpdk application to the kernel. Furthermore, the vlan/macvlan/ipvlan cni plugins were modified to create subinterfaces from a master interface located in the container.

Description::

Telecom customers are very security conscious and require clusters to be hardened against multiple attack vectors. Within OpenShift there is no single component or feature responsible for securing a cluster. This section provides details of security oriented features and configuration for the use models covered in this specification

* SecurityContextConstraints – All workload pods should be run with restricted-v2 or restricted SCC.
* Seccomp – All pods should be run with RuntimeDefault (or stronger) seccomp profile.
* Secureboot – TBD
* Rootless DPDK pods – Many user-plane networking (DPDK) CNFs require pods to run with root privileges. Under this feature a conformant DPDK pod can be run without requiring root privileges.
* The storage network should be isolated and non-routable to other cluster networks. See the Storage section for additional details.

Limits and requirements::

* Rootless DPDK pods requires the following additional configuration
** The tap plugin to be configured with the container_t SELinux context.
** Enable the container_use_devices SELinux boolean on the hosts.
** Add the supplementary group ID 801 by either setting the fsGroup security context in the pod definition or adding this group to the user running the image.

Engineering considerations::

* For rootless DPDK pod support, the SELinux boolean container_use_devices must be enabled on the host for the tap device to be created. This introduces a security risk that for the short/mid term is acceptable. Other solutions will be explored.