// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-ran-ref-design-spec.adoc

:_content-type: CONCEPT
[id="telco-core-whats-new-ref-design_{context}""]
= What's new in {product-title} {product-version} for telco core

The following new features included in {product-title} {product-version} are leveraged by the telco core reference design.

.New features for telco core in {product-title} {product-version}
[cols="1,3", options="header"]
|====
|Feature
|Description

//CNF-7349 Rootless DPDK pods
|Support for running rootless DPDK workloads with kernel access by using the TAP CNI plugin
a|DPDK applications that need to inject some traffic to the kernel can run in non-privileged pods with the help of the TAP CNI plugin.

* link:https://docs.openshift.com/container-platform/4.14/networking/hardware_networks/using-dpdk-and-rdma.html#nw-running-dpdk-rootless-tap_using-dpdk-and-rdma[Using the TAP CNI to run a rootless DPDK workload with kernel access]

//CNF-5977 Better pinning of the networking stack
|Dynamic use of non-reserved CPUs for OVS
a|With this release, the Open vSwitch (OVS) networking stack can dynamically use non-reserved CPUs.
This dynamic use of non-reserved CPUs occurs by default in performance-tuned clusters with a CPU manager policy set to `static`.
The dynamic use of available, non-reserved CPUs maximizes compute resources for OVS and minimizes network latency for workloads during periods of high demand.
OVS remains unable to dynamically use isolated CPUs assigned to containers in `Guaranteed` QoS pods. This separation avoids disruption to critical application workloads.

//CNF-7760
|Enabling more control over the C-states for each pod
a|You have more control over the C-states for your pods. Now, instead of disabling C-states completely, you can specify a maximum latency in microseconds for C-states. You can configure this option in the `cpu-c-states.crio.io` annotation, which helps to optimize power savings in high-priority applications by enabling some of the shallower C-states instead of disabling them completely.

* link:https://docs.openshift.com/container-platform/4.14/scalability_and_performance/cnf-low-latency-tuning.html#node-tuning-operator-pod-power-saving-config_cnf-master[Optional: Power saving configurations].


//CNF-7741 Permit to disable NUMA Aware scheduling hints based on SR-IOV VFs
|Exclude SR-IOV network topology for NUMA-aware scheduling.
a|You can exclude advertising the Non-Uniform Memory Access (NUMA) node for the SR-IOV network to the Topology Manager. By not advertising the NUMA node for the SR-IOV network, you can permit more flexible SR-IOV network deployments during NUMA-aware pod scheduling.

For example, in some scenarios, it is a priority to maximize CPU and memory resources for a pod on a single NUMA node. By not providing a hint to the Topology Manager about the NUMA node for the pod’s SR-IOV network resource, the Topology Manager can deploy the SR-IOV network resource and the pod CPU and memory resources to different NUMA nodes. In earlier {product-title} releases, the Topology Manager attempted to place all resources on the same NUMA node only.

* link:https://docs.openshift.com/container-platform/4.14/networking/hardware_networks/configuring-sriov-device.adoc#nw-sriov-exclude-topology-manager_configuring-sriov-device[Exclude the SR-IOV network topology for NUMA-aware scheduling]

//CNF-8035 MetalLB VRF Egress interface selection with VRFs (Tech Preview)
|Egress service resource to manage egress traffic for pods behind a load balancer (Technology Preview)
a|With this update, you can use an `EgressService` custom resource (CR) to manage egress traffic for pods behind a load balancer service. This is available as a Technology Preview feature.

You can use the `EgressService` CR to manage egress traffic in the following ways:

* Assign the load balancer service's IP address as the source IP address of egress traffic for pods behind the load balancer service.

* Assign the egress traffic for pods behind a load balancer to a different network than the default node network.

* link:https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/configuring-egress-traffic-for-vrf-loadbalancer-services.adoc#configuring-egress-traffic-loadbalancer-services[Configuring an egress service].

|====