// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-core-ref-components.adoc

:_content-type: REFERENCE
[id="telco-core-power-management_{context}"]
= Power Management

New in this release::
* Ability to specify a maximum latency (i.e. C-state) for a low latency pod when using per-pod power management. Previously c-states could only be disabled completely on a per pod basis.

// https://issues.redhat.com/browse/CNF-7760

Description::

The https://docs.openshift.com/container-platform/latest/rest_api/node_apis/performanceprofile-performance-openshift-io-v2.html#spec-workloadhints[Performance Profile] can be used to configure a cluster in a high power, low power or mixed (https://docs.openshift.com/container-platform/latest/scalability_and_performance/cnf-low-latency-tuning.html#node-tuning-operator-pod-power-saving-config_cnf-master[per-pod power management]) mode. The choice of power mode will depend on the characteristics of the workloads running on the cluster - particularly how sensitive they are to latency.

Limits and requirements::
* Power configuration relies on appropriate BIOS configuration for example enabling C-states and P-states which varies between hardware vendors.


Engineering considerations::
* Latency - workloads that are particularly sensitive to latency will require either a high power or per-pod power management configuration in order to ensure that the latency requirements are met. Per-pod power management is only available for Guaranteed QoS Pods with dedicated pinned CPUs.
