// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-core-ref-components.adoc

:_content-type: REFERENCE
[id="telco-core-monitoring_{context}"]
= Monitoring

New in this release::


Description::

The Cluster Monitoring Operator is included by default on all OpenShift clusters and provides monitoring (metrics, dashboards, and alerting) for the platform components and optionally user projects as well.

Configuration of the monitoring operator allows for customization including

* Default retention period
* Custom alert rules

The default handling of pod CPU and memory metrics (based on upstream Kubernetes/cAdvisor) makes a tradeoff which prefers handling of stale data over metric accuracy. This leads to spiky data which will create false triggers of alerts over user specified thresholds. OpenShift supports an opt-in Dedicated Service Monitor feature which creates an additional set of pod CPU/memory metrics which do not suffer from the spiky behavior. More details are covered in https://access.redhat.com/solutions/7012719[this solution guide].

In addition to default configuration, the following metrics are expected to be configured for Telco core clusters:

* Pod CPU and memory metrics and alerts for user workloads

Limits and requirements::

* Monitoring configuration must enable the Dedicated Service Monitor feature for accurate representation of pod metrics

Engineering considerations::

* The Prometheus retention period is specified by the user. The value used is a tradeoff between operational requirements for maintaining historical data on the cluster against CPU and storage resources. Longer retention periods increase the need for storage and require additional CPU to manage the indexing of data.

