// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-core-ref-components.adoc

:_content-type: REFERENCE
[id="telco-core-cluster-network-operator_{context}"]
= Cluster Network Operator (CNO)

New in this release::


Description::

The CNO deploys and manages the cluster network components including default OVN-Kubernetes network plugin during OCP cluster installation. It allows configuring primary interface MTU settings, OVN gateway modes to use node routing tables for pod egress, and additional secondary networks such as MACVLAN.

In support of network traffic segregation multiple network interfaces are configured through the CNO. Traffic steering to these interfaces is configured through static routes applied via the NMState configuration/operator. To ensure that Pod traffic is properly routed OVN-K is configured with the routingViaHost option enabled. This setting uses the kernel routing table (and thus the applied static routes) rather than OVN for Pod egress traffic.

The Whereabouts CNI plugin is used to provide dynamic IPv4 and IPv6 addressing for additional (non-primary) pod network interfaces without the use of a DHCP server.

Limits and requirements::

* OVN-Kubernetes is required for IPv6 support
* Large MTU cluster support requires connected network equipment to be set to the same or larger value.

Engineering considerations::
* Pod egress traffic is handled by kernel routing table (routingViaHost option). Appropriate static routes must be configured in the host.

