// Module included in the following assemblies:
//
// * telco_ref_design_specs/ran/telco-core-ref-components.adoc

:_content-type: REFERENCE
[id="telco-core-load-balancer_{context}"]
= Load Balancer

New in this release::

Not applicable.

Description::

MetalLB is a load-balancer implementation for bare metal Kubernetes
clusters using standard routing protocols. It enables a kubernetes
service to get an external IP address which is also added to the host
network for the cluster.

* MetalLB is a load-balancer implementation for bare metal Kubernetes
clusters using standard routing protocols. It enables a kubernetes
service to get an external IP address which is also added to the host
network for the cluster.

Some use cases may require features not available in MetalLB, eg
stateful load balancing. Where necessary an external/3rd party load
balancer may be used. Selection and configuration of an external load
balancer is outside the scope of this specification. When an
external/3rd party load balancer is used the integration effort must
include sufficient analysis to ensure all performance and resource
utilization requirements are met.

Limits and requirements::

* Stateful load balancing is not supported by Metal LB. An alternate load
balancer implementation must be used if this is a requirement for
workload CNFs.
* The networking infrastructure must ensure that the external IP address
is routable/reachable from clients to the host network for the cluster.

Engineering considerations::
* MetalLB is used in BGP mode only for Core use models.
* For Core use models MetalLB is supported with only the OVN-Kubernetes
network provider used in local gateway mode see `routingViaHost` in
the Cluster Network Operator section.
* BGP configuration in MetalLB is expected to vary depending on the
requirements of the network and peers.
* Address pools may be configured as needed with variation in addresses,
aggregation length, auto assignment, etc
* Parameters in the BFD profile may be values should remain close to the
defaults. Shorter values may lead to false negatives and impact
performance.


