DirectoryPath: "_preview/"
EnforceHTTPS: true
OutputDirectory: "tmp/.htmltest"
ExternalTimeout: 60 # (seconds) default is 15
IgnoreURLs: []
IgnoreDirs: []
LogLevel: 1 # or use "info" for more verbose logging
CheckAnchors: false
CheckExternal: true
CheckFavicon: false
CheckGeneric: false
CheckImages: false
CheckInternal: true
CheckInternalHash: false
CheckMetaRefresh: false
CheckRobotsTxt: false
CheckScripts: false
IgnoreEmptyHref: true
ignoreFragments: true
IgnoreInternalEmptyHash: true
