---
DirectoryPath: "_preview/"
IgnoreFragments: true
CheckInternal: false


OutputDirectory: "tmp/.htmltest"
CacheExpires: "12h" # Default is 2 weeks.
ExternalTimeout: 60 # (seconds) default is 15.
# Ignore URLs that start with ../ (Doesn't work?)
IgnoreURLs:
  - "\\.\\./.*"
