language: python
cache:
  pip: true
  directories:
    - /home/travis/.rvm/gems

git:
  depth: 10
jobs:
  include:
      name: "Preview, validate, and build"
      before_install:
        - chmod +x ./scripts/changed-files.sh
        - ./scripts/changed-files.sh
      install:
        - gem install asciidoctor asciidoctor-diagram rouge
        - pip3 install pyyaml aura.tar.gz
      script:
        # Fail if Asciidoctor encounters errors. Pass otherwise. Then, build updated distros
        - chmod +x ./scripts/check-asciidoctor-build.sh
        - chmod +x ./scripts/get-updated-distros.sh
        - ./scripts/check-asciidoctor-build.sh || travis_terminate 1
        - |
          ./scripts/get-updated-distros.sh | while read -r filename; do
            case "$filename" in
              "_topic_maps/_topic_map.yml")
                echo "OpenShift Container Platform"
              ;;
              "_topic_maps/_topic_map_osd.yml")
                echo "OpenShift Dedicated"
              ;;
              "_topic_maps/_topic_map_ms.yml")
                echo "Microshift"
              ;;
              "_topic_maps/_topic_map_rosa.yml")
                echo "Red Hat OpenShift Service on AWS"
              ;;
              "_distro_map.yml")
                echo "OpenShift Container Platform from _distro_map.yml"
              ;;
              *)
                echo "NO MATCH: $filename"
              ;;
            esac
          done

          if [ -d "drupal-build" ]; then python3 makeBuild.py; fi