language: python
cache:
  pip: true

git:
  depth: 10
jobs:
  include:
    - name: "Preview, validate, and build"
      before_install:
      - if [ "$TRAVIS_BRANCH" != "main" ]; then chmod +x autopreview.sh && ./autopreview.sh; fi
      install:
        - gem install --local _gemfiles/asciidoctor-2.0.20.gem _gemfiles/asciidoctor-diagram-plantuml-1.2023.10.gem _gemfiles/asciidoctor-diagram-ditaamini-1.0.3.gem _gemfiles/rexml-3.2.6.gem _gemfiles/asciidoctor-diagram-2.2.14.gem _gemfiles/rouge-4.1.3.gem
        - pip3 install pyyaml aura.tar.gz
      script:
        # Fail if Asciidoctor encounters errors. Pass otherwise. Then, build updated distros
        - chmod +x ./scripts/check-asciidoctor-build.sh
        - ./scripts/check-asciidoctor-build.sh
        - python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.15 --no-upstream-fetch
        - python3 build.py --distro openshift-dedicated --product "OpenShift Dedicated" --version 4 --no-upstream-fetch
        - python3 build.py --distro openshift-rosa --product "Red Hat OpenShift Service on AWS" --version 4 --no-upstream-fetch
        - python3 build.py --distro microshift --product "Microshift" --version 4 --no-upstream-fetch
        - python3 build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 4.15 --no-upstream-fetch
        - python3 makeBuild.py
