:_content-type: ASSEMBLY
[id="telco-ran-rds-overview"]
= Telco core use case model overview
include::_attributes/common-attributes.adoc[]
:context: ran-core-design-overview

toc::[]

The use model for a telco core cluster provides a platform supporting large scale telecom applications including control plane (signaling, aggregation, and so on) and some centralized data plane for example user plane functions (UPF) functions running on commodity hardware. For examples of these functions see the architecture diagram. These functions generally require scalability, complex networking support, resilient software-defined storage, and support performance requirements that are less stringent and constrained than far-edge deployments like RAN.

The networking prerequisites for core telco functions exhibit large diversity, encompassing an array of networking attributes and performance benchmarks. IPv6 is mandatory, with dual-stack configurations being prevalent. Certain functions demand maximum throughput and transaction rates, necessitating user-plane networking support, such as DPDK. Other functions adhere to conventional cloud-native patterns and can use solutions like OVN-K, kernel networking, and load balancing.

Telco core clusters are configured as standard 3-control plane plus N worker nodes configured with the stock non real-time (RT) kernel. In support of workloads with varying networking and performance requirements the worker nodes are segmented into MachineConfigPools for example non-user-dataplane compared to high-throughput nodes. In support of the required telecom operational features the clusters have a standard set of Operator Lifecycle Manager (OLM) day-2 operators installed.

include::modules/telco-core-ref-design-baseline-model.adoc[leveloffset=+1]

include::modules/telco-core-ref-eng-usecase-model.adoc[leveloffset=+2]

include::modules/telco-core-ref-application-workloads.adoc[leveloffset=+2]

