:_content-type: ASSEMBLY
[id="telco-ran-rds-overview"]
= Telco core use case model overview
include::_attributes/common-attributes.adoc[]
:context: ran-core-design-overview

toc::[]

The use model for a telco Core cluster is to provide a platform supporting large scale telecom applications including control plane (signaling, aggregation, …) and some centralized data plane (eg UPF) functions running on commodity hardware. For examples of these functions see the architecture diagram above. These functions will generally require scalability, complex networking support, resilient software-defined storage, and support performance requirements that are less stringent and constrained than far-edge (eg RAN) deployments.

The networking requirements of telco core functions vary widely across a range of networking features and performance points. IPv6 is a requirement and dual-stack is common. Some functions need maximum throughput and transaction rate and require support for user-plane networking (DPDK) while others make use of more typical cloud-native patterns and can rely on OVN-K, kernel networking and load balancing.

Telco core clusters are configured as standard 3-control plane + N worker nodes configured with the stock (non-RT) kernel. In support of workloads with varying networking and performance requirements the worker nodes are segmented into MachineConfigPools (eg non-user-dataplane vs high-throughput). In support of required telecom operational features the clusters have a standard set of OLM (day-2) operators installed.

include::modules/telco-core-ref-design-baseline-model.adoc[leveloffset=+1]

include::modules/telco-core-ref-eng-usecase-model.adoc[leveloffset=+2]

include::modules/telco-core-ref-application-workloads.adoc[leveloffset=+2]

