name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install AsciiDoctor
        run: gem install asciidoctor

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build site
        run: ./scripts/build-mkdocs-site.sh --build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ../public

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/mkdocs
          key: mkdocs-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
